**UTS MACHINE LEARNING**

Izza Rizkya Azzahra

4112322001

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import GridSearchCV

import warnings
warnings.filterwarnings('ignore')


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
train_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data_training.csv')
test_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data_testing.csv')

In [4]:
train_data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.3             0.740         0.08             1.7      0.094   
1            8.1             0.575         0.22             2.1      0.077   
2           10.1             0.430         0.40             2.6      0.092   
3           12.9             0.500         0.55             2.8      0.072   
4            8.4             0.360         0.32             2.2      0.081   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 10.0                  45.0  0.99576  3.24       0.50   
1                 12.0                  65.0  0.99670  3.29       0.51   
2                 13.0                  52.0  0.99834  3.22       0.64   
3                  7.0                  24.0  1.00012  3.09       0.68   
4                 32.0                  79.0  0.99640  3.30       0.72   

   alcohol  quality    Id  
0      9.8        5  1366  
1      9.2        5   103  
2     10.0        7   942  
3     10.9        6   811  
4     11.0        6   918

In [5]:
train_data.quality.value_counts()

quality
5    362
6    341
7    109
4     26
8     13
3      6
Name: count, dtype: int64

In [6]:
train_data.shape

(857, 13)

In [7]:
test_data.shape

(286, 12)

In [8]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 857 entries, 0 to 856
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         857 non-null    float64
 1   volatile acidity      857 non-null    float64
 2   citric acid           857 non-null    float64
 3   residual sugar        857 non-null    float64
 4   chlorides             857 non-null    float64
 5   free sulfur dioxide   857 non-null    float64
 6   total sulfur dioxide  857 non-null    float64
 7   density               857 non-null    float64
 8   pH                    857 non-null    float64
 9   sulphates             857 non-null    float64
 10  alcohol               857 non-null    float64
 11  quality               857 non-null    int64  
 12  Id                    857 non-null    int64  
dtypes: float64(11), int64(2)
memory usage: 87.2 KB


In [ ]:
#pengecekan missing value
train_data.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [ ]:
#cek jumlah data yg duplikat
train_data.duplicated().sum()

np.int64(0)

In [32]:
#split data untuk validasi
X = train_data.drop(['quality', 'Id'], axis=1)
y = train_data['quality']

- Fitur x adalah semua kolom kecuali target (quality) dan Id.
- Label y adalah kolom quality yang akan diprediksi

In [33]:
X_train, X_val, y_train, y_val = train_test_split (X, y, test_size=0.2, random_state=42)

Membagi data training menjadi 80% data latih dan 20% data validasi agar kita bisa mengevaluasi model sebelum digunakan ke data testing.

In [25]:
# training random forest
rf = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
rf.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

membangun model random forest
- n_estimators=100: jumlah pohon dalam hutan
- class_weight='balanced': menangani data yang tidak seimbang antar kelas kualitas anggur
- random_state=42: untuk hasil yang konsisten.

In [26]:
#evaluasi model
y_pred = rf.predict(X_val)

In [27]:
#Tampilkan Hasil
print("Accuracy:", accuracy_score(y_val, y_pred))

Accuracy: 0.622093023255814


In [28]:
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred))
print("Classification Report:\n", classification_report(y_val, y_pred))

Confusion Matrix:
 [[ 0  1  2  0  0]
 [ 1 45 21  0  0]
 [ 0 23 52  3  0]
 [ 0  1 10 10  0]
 [ 0  0  1  2  0]]
Classification Report:
               precision    recall  f1-score   support

           4       0.00      0.00      0.00         3
           5       0.64      0.67      0.66        67
           6       0.60      0.67      0.63        78
           7       0.67      0.48      0.56        21
           8       0.00      0.00      0.00         3

    accuracy                           0.62       172
   macro avg       0.38      0.36      0.37       172
weighted avg       0.61      0.62      0.61       172



In [30]:
#prediksi data testing
X_test = test_data.drop('Id', axis=1)
test_pred = rf.predict(X_test)

menggunakan model terlatih untuk memprediksi kualitas anggur pada data uji yang tidak memiliki label quality.

In [34]:
submission = pd.DataFrame({'Id': test_data ['Id'],'Quality': test_pred})
submission.to_csv('hasilprediksi_001.csv', index=False)

Menyimpan hasil prediksi ke file CSV sesuai format yang diminta, yaitu hanya memuat kolom Id dan Quality